[[chapter2]]
= Registers

== Scalar register

. *VCSR* (Vector Control and Status Register)
+
Add new fields to the vector control and status register (vcsr) to control the fixed-point multiplication with shift, fixed-point accumulation with shift, and funnel shift related instructions.

* _mulsft_ (multiply shift) controls the right shift operation after the multiplier operation. The right shift operation is round shift, and the round mode is controlled by vxrm. 

* _accsft_ (accumulated shift) controls the right shift operation of the accumulation operation. The shift operation is round shift, and the round mode is controlled by vxrm. 

* _fsft_ configures the shift length of the funnel shift, so that the operation can realize flexible funnel shift function without increasing the source operand.
+

.VCSR bit fields table
[cols="3*", options="header"]
|====================================
| Bitfield  | Name  | Description          
| 31:18 | rsv          | reserve        
| 17:13 | fsft         | elements num. of funnel shift   
| 12:8  | accsft[12:8] | accumulation shift，0 ~ 31 
| 7:3   | mulsft[7:3]  | multiply shift，0 ~ 31 
| 2:1   | vxrm[1:0]    | rounding mode  
| 0     | vxsat        |             
|====================================

. *VNLCR* (Vector non-linear Control Register)
+
This register is used to configure the function type and segmentation information of the nonlinear function. The register width is 32 bits, configured through the Zicsr extended instruction, address _0x00E_.

* _FuncId_ configures the type of the current nonlinear function; If the configured funcId is out of the scope, default process will be selected.

* _SegCnt_ configures the number of segments of the nonlinear function. The maximum number of segments of the nonlinear function is 16. Only lowest two bits (16th and 17th) are available. 
+
.VNLCR bit fields table
[cols="3*", options="header"]
|==============================
| Bitfield  | Name  | Description       
| 31:16 | SegCnt |segments num. of non-linear function.  0: 4 segments; 1：8 segments; 2：12 segments; 3：16 segments 
| 15:0  | funcId    | non-linear function ID. 0：reciprocal; 1: square root; 2: reciprocal of square root; 3: log2; 4: arctan; 5: log10; 6: sin; 7: cos;
|==============================

. *VCPFLAG* (Vector coprocessor flag register)
+
This register is used by coprocessor to feedback status information, read by processor for debug purpose. Its bits field definition are total custom definition. The address is _0x00C_.

. *VCPCTRL* (Vector coprocessor control register)
+
This register is programmed by processor to control coprocessor's behavior. coprocessor read this register as input parameters. Its bits field definition are totally custom definition. The address is _0x00D_.

== Vector registers

. *vnlpr0*  (1024bits vector non-linear paramter register 0)
+
The segmentation information of the nonlinear function is stored through the parameter configuration registers vnlpr0 and vnlpr1. The length of vnlpr0 and vnlpr1 is 1024bits. This register is configured through the vlnlp instruction. +
+
[cols="2*", options="header"]
|================================
|    R_NL_A[16]   |   R_NL_B[16]
|================================

. *vnlpr1*  (1024bits vector non-linear paramter register 1)
+
[cols="2*", options="header"]
|================================
| R_NL_SEG_EXP[16] | R_NL_SEG[16]
|================================
+
- R_NL_SEG[16]: 16 nonlinear function segment fix points registers
- R_NL_SEG_EXP[16]: R_NL_SEG_EXP(0) stores the fix point position of R_NL_A[16] and R_NL_B[16]; R_NL_SEG_EXP(1) stores the fix point position of fitting result; - R_NL_SEG_EXP(2) stores the fix point position of R_NL_SEG[16]
- R_NL_A[16]: 16 nonlinear function segement slope registers
- R_NL_B[16]: 16 nonlinear function segement offset registers


