[[chapter1]]
== Zvw basic rules

*Currently, there are some limitations for Zvw* 

* *It only supports RV32 and SEW=32bits, when SEW=32 SC16 is supported.*
* *SC32 is not supported, 32 real and imaginary parts of complex number are stored in neighbor vector registers.*  
* *The operations defined for each vector element in following instruction behavior follow RVV1.0 rule, inlcudeing but not limited to LMUL/VL/vm/ta/ma operation rules.Any new operation not specified follows RVV 1.0 rules.*
* *For any '.vs' instruction, the 'v' register increase index while LMUL > 1, but 's' vector register don't increase index when LMUL > 1.* 
* *All Zvw instruction only supports signed integer operations. except uimm values.*

== Basic definition

. *Data types*
+
- int8: 8 bit signed char 
- int16: 16 bit signed half word
- int32: 32 bit word
- sc16: signed complex with 16bits image and 16bits real part, real part in low 16bit. e.g. 0xFFFD0005, image = -3, real = 5

. *Operations*
+
- get_e: Get the exponent part in the Complex Packed Float-point format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the exponent part is at highest bits, get_e(0x3F45) = 0b'0011' 
- get_i: Get the imaginary part in the Complex Packed Float-point format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the image part is the 6 bits after exponent bits, get_i(0x3F45) = 0b'111101'
- get_r: Get the real part in the complex compressed format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the real part is the lowest 6 bits, get_r(0x3F45) = 0b'000101'
- zp16: Add 0 to 16 bits at lowest bits. e.g.zp16(0b'111101') = 0b'1111010000000000'
- zp32: Add 0 to 32 bits at lowest bits. e.g.zp32(0b'111101') = 0b'11110100000000000000000000000000'
- sx16: sign extension to 16 bits. e.g. sx16(0b'111101') = 0xFFFD.
- sx32: sign extension to 32 bits. e.g. sx16(0b'111101') = 0xFFFFFFFD.
- min: Find the minimum value from vector registers.
- max: Find the maximum value from vector registers.
- min_i: Find the element index in the vector registers where the minimum value is located. If there are multiple element equal to minimum value, return the index of the right most and lowest vr index one.
- max_i: Find the element index in the vector registers where the maximum value is located. If there are multiple element equal to maximum value, return the index of the right most and lowest vr index one.
- lsb: The number of leading sign bit minus 1 for the absolute value of input. e.g. lsb( 0b'00010010') = 2, lsb( 0b'11111111') = lsb(abs(0b'11111111')) = lsb(0b'00000001') = 6; lsb(0b'00000000') = 0.
- cpf_pack: Put e, i and r into the compressed complex format according to the complex compressed format. e.g. cpf_pack(e=0x3, i=0xFFFD, r=0x5) = 0x3F45
- vcpack: extract the high 16 bits of 32-bit real numbers and 32-bit imaginary numbers in rounding mode to form a complex number in SC16 format. e.g i = 0x00058000, r = 0x00038000, vcpack(0x00058000, 0x00038000) = 0x00060004
- sum: sum(star, end) sum all element from start index to end index, star and end inclusive. the result will sign extend to 2 SEW width.
- abs: compute the absolute value of input
- conj: Convert a complex to it's conjugate complex. when min negative S16 value coverted to max positive S16 value it should saturated to 0x7fff. e.g. conj(0x80007fff) = 0x7fff7fff.
- alg_round_shift_right: Arithmetic right shift with vxrm mode rounding, e.g. vxrm=rnu, alg_round_shift_right(0x0005, 1) = 0x3
- alg_shift_left: Arithmetic left shift with Saturate. 
- alg_shift_right: Arithmetic right shift without rounding. e.g. alg_shift_right(0x0005, 1) = 0x2
- shift_left: Logical left shift.
- clip_low_x_y:  Saturate and clip the lowest y width bits from a x bits number. e.g. x=40bits, y=32bits, clip_low_40_32(0x0050000000) = 0x50000000; clip_low_40_32(0x0080000000) = 0x7fffffff.
- round_clip_high_x_y: Saturate clip the high y width bits number with vxrm mode rounding. e.g. x=40bits, y=32bits,round_clip_high_40_32(0x0050000381) = 0x00500004, round_clip_high_40_32(0x7fffffff80) = 0x7fffffff.
- vmem: vmem(vr, addr) store the numbers of VR into vector memory indicated by "addr".

. *Register index*
+
- i: the element index within a vector register. value range [0, 31].
- j: the consecutive VR index when LMUL set to a value bigger than 1. value range [0, 7], support max LMUL = 8;
- .i: get the image part of SC data type
- .r: get the real part of SC data type

. *Internal registers*

- ACCREG[i]: The i-th accumulation register inside the MAC ALU, 80 bits signed integer or 40bit signed image and real for complex value, 32 elements in total.
- MULSFTREG[j][i]: The j-th multiply shift register i-the element inside the MAC ALU, 5bits unsigned value per element, 8*32 elements in total.
