[[chapter7]]
== Dynamic scaling Reduced operation

=== vdsredsum(vector dynamic scaling reduced sum)
. *Grammar*
+
vdsredsum.v vd, vs2, vm +

. *Purpose*
+
Each element in the vector register is accumulated and then shifted to the right dynamically, and the output width remains unchanged.

. *Description*
+
The elements in vs2 are accumulated and the accumulated value is dynamically shifted to the right by round arithmetic and then the low SEW bit is intercepted and output to vd[0][0].

. *Operation*
+
----
Tmp = 0；
j = 0;
nj = (vl + (VLEN/SEW) - 1) / (VLEN/SEW)
For each j < nj
   For each i in vs2[j] AND (j * (VLEN/SEW) + i) < vl
        Tmp += v0.b[i] == 0 ? 0 : vs2[j][i]  // 2SEW = SEW

vd[0][0] = clip_low_SEW(alg_round_shift_right(tmp, accsft)) // SEW = 2SEW
----

=== vdsredsumn(vector dynamic scaling reduced sum for each n element)
. *Grammar*
+
vdsredsumn.vs vd, vs2, rs1 +
vdsredsumn.vi vd, vs2, uimm +

. *Purpose*
+
Every n elements in the vector register are accumulated and then round shifted before output, where n is the power of an integer of 2.

. *Description*
+
Every 2^rs1 or 2^uimm elements in vs2 are accumulated and then do algorithm round right shift before output to vd. rs1 and uimm valid value are [1, 2, 3, 4].

. *Operation*
+
----
VS version

n = 2^rs1
j = 0
i = 0
l =0 
VELE = (VLEN/SEW)
nj = (vl + VELE - 1) / VELE
nres = vl - (vl/VELE) * VELE
For each j < nj
    maxEle = (j == (nj - 1)) ? nres : VELE
    maxSeg = (maxEle + n - 1)/n
    For (k = 0; k < maxSeg; k++)
        start = k * n
        end = min(k * n + n - 1, maxEle)
        temp  = sum(vs2[j][start ... end]) //2SEW = SEW
        vd[l][i] = clip_low_SEW(alg_round_shift_right(temp, accsft)); //SEW = 2SEW
        i++
        if i == VELE
            i = 0
            l++
}

VI version

n = 2^uimm;
j = 0
i = 0
l =0 
VELE = (VLEN/SEW)
nj = (vl + VELE - 1) / VELE
nres = vl - (vl/VELE) * VELE
For each j < nj
    maxEle = (j == (nj - 1)) ? nres : VELE
    maxSeg = (maxEle + n - 1)/n
    For (k = 0; k < maxSeg; k++)
        start = k * n
        end = min(k * n + n - 1, maxEle)
        temp  = sum(vs2[j][start ... end]) //2SEW = SEW
        vd[l][i] = clip_low_SEW(alg_round_shift_right(temp, accsft)); //SEW = 2SEW
        i++
        if i == VELE
            i = 0
            l++
}
----

=== vredmaxi(vector reduced max with index)
. *Grammar*
+
vredmaxi.vv vd, vs2, vs1, vm +

. *Purpose*
+
Find the maximum value in the vector register and its corresponding index value, then output it to the first and second elements in the target register.
In parallel, it updates the MSKREG status by seting 0 to the bit that corresponds to the max value.

. *Description*
+
vs2 saves the input value, vs1 saves the index value corresponding to each input value, finds the maximum value in vs2 and writes it into vd[0], and its corresponding index value is written into vd[1]. If the maximum value appears in multiple locations, output The first maximum value searched from low element to high element into vd. In parallel, it updates the MSKREG status by seting 0 to the bit that corresponds to the max value. Default max value is the same as RVV 1.0, default index value is 0.

. *Operation*
+
----
vd[0][0] = max(vs2, MSKREG); 
k = max_k(vs1, MSKREG); // First maximum value searched from lowest element of lowest VR
MSKREG[k] = 0;
vd[0][1] = vs1[k];
----

=== vredmini(vector reduced min with index)
. *Grammar*
+
vredmini.vv vd, vs2, vs1, vm +

. *Purpose*
+
Find the minimum value in the vector register and its corresponding index value and output it to the first and second elements in the target register.

. *Description*
+
vs2 saves the input value, vs1 saves the index value corresponding to each input value, finds the minimum value in vs2 and writes it into vd[0], and its corresponding index value is written into vd[1]. If the minimum value appears in multiple locations, output The first minimum value searched from low element to high element into vd. Default min value is the same as RVV 1.0, default index value is 0.

. *Operation*
+
----
vd[0][0] = min(vs2, MSKREG); 
k = min_i(vs1, MSKREG); //First minimum value searched from lowest element
MSKREG[k] = 0;
vd[0][1] = vs1[k];
----

=== vmget(vector mask get and write to v0)
. *Grammar*
+
vmget.v v0 +

. *Purpose*
+
Get the 1024bits mask from MSKREG and write it to low 1024bits of V0.

. *Description*
+
Read the 1024bits mask from MSKREG and write it to low 1024bits of V0. v0 is the vd, no vs1 and vs2, don't support vm.

. *Operation*
+
----
V0 = MSKREG;
----

=== vmset(vector mask set from v0 to MSKREG)
. *Grammar*
+
vmset.v v0 +

. *Purpose*
+
set the 1024bits mask from V0 low 1024bits to MSKREG.

. *Description*
+
set the 1024bits mask from V0 low 1024bits to MSKREG. v0 is the vs1, no vs1 and vd, don't support vm.

. *Operation*
+
----
MSKREG = v0;
----

.
